// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXtqKYB06st8j5DEAZnA1TKVsdR-l70o',
    appId: '1:822028744441:web:2a3d182e3529f9853a9428',
    messagingSenderId: '822028744441',
    projectId: 'betta-store',
    authDomain: 'betta-store.firebaseapp.com',
    storageBucket: 'betta-store.appspot.com',
    measurementId: 'G-FM9BPN03GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKB7bBDOgW5n-_J6JmvGR2SKrzXnf-nNA',
    appId: '1:822028744441:android:55dd88864c67ac133a9428',
    messagingSenderId: '822028744441',
    projectId: 'betta-store',
    storageBucket: 'betta-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLXwY_Pv6J9doQIzGUXahMSfJza4CfQcw',
    appId: '1:822028744441:ios:bfe2017a494eaea83a9428',
    messagingSenderId: '822028744441',
    projectId: 'betta-store',
    storageBucket: 'betta-store.appspot.com',
    iosBundleId: 'com.example.bettaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLXwY_Pv6J9doQIzGUXahMSfJza4CfQcw',
    appId: '1:822028744441:ios:5e35e5465fb480803a9428',
    messagingSenderId: '822028744441',
    projectId: 'betta-store',
    storageBucket: 'betta-store.appspot.com',
    iosBundleId: 'com.example.bettaStore.RunnerTests',
  );
}
